/**
 * Projekt do předmětu PDB (2016/2017) - Prostorové, multimediální a temporální 
 * databáze: Metro Accident Databse
 * Autoři: Petr Staněk (xstane34), 
           František Matečný (xmatec00),
           Jakub Stejskal (xstejs24)
 * Datum:  12.12.2016
 * Verze:  1.0
 */
package GUI.TABS;

import GUI.WINDOW.Incident;
import LOGIC.Incident.TIncident;
import LOGIC.Incident.ValidateForm;
import DB.Queries.Spatial;
import GUI.MYOBJECTS.DateLabelFormatter;
import GUI.MYOBJECTS.MyComboBox;
import GUI.Main;
import GUI.PANELS.MapSearchViewer;
import java.awt.Component;
import java.util.Properties;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.SqlDateModel;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 * Třída pro vyhledávání incidentů.
 * @author petr
 */
public class Search extends javax.swing.JPanel {
	private TIncident ta = new TIncident(); // struktura s hodnotami formuláře
	private JDatePickerImpl datePicker1; // datepicker datum od
    private JDatePickerImpl datePicker2; // datepicker datum do
    
	/**
     * Vytvoří záložku pro vyhledávání incidentů.
     */
    public Search() {
        initComponents();             
		jScrollPane3.getVerticalScrollBar().setUnitIncrement(16);
		
		// inicializace polí pro datum 
		Calendar c = Calendar.getInstance();
		int mYear = c.get(Calendar.YEAR);
		int mMonth = c.get(Calendar.MONTH);
		int mDay = c.get(Calendar.DAY_OF_MONTH);

		datePicker1.getModel().setDate(mYear, mMonth-1, mDay);
		datePicker1.getModel().setSelected(true);
		datePicker2.getModel().setDate(mYear, mMonth, mDay);
		datePicker2.getModel().setSelected(true);
		
		// automatické vyhledání při spuštění
		searchIncidents();
		// načtení celé mapy
		 Spatial.loadObjectFromDb();
   
    }
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateFrom = new javax.swing.JPanel();
        dateTo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        station = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        line = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        area = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        event = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        reason = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        injury = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sex = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jBtnSearch = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        age = new javax.swing.JTextField();
        delay = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mapSearchViewer1 = new GUI.PANELS.MapSearchViewer();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            @Override
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
                Component component = super.prepareRenderer(renderer, row, column);
                int rendererWidth = component.getPreferredSize().width;
                TableColumn tableColumn = getColumnModel().getColumn(column);
                tableColumn.setPreferredWidth(Math.max(rendererWidth + getIntercellSpacing().width, tableColumn.getPreferredWidth()));
                return component;
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBtnNewIncident = new javax.swing.JButton();
        jBtnDelFound = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel1.setBorder(null);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setText("Evidenční číslo");

        id.setMaximumSize(new java.awt.Dimension(112, 2147483647));
        id.setPreferredSize(new java.awt.Dimension(112, 27));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setText("Datum");

        dateFrom.setMaximumSize(new java.awt.Dimension(112, 2147483647));
        dateFrom.setMinimumSize(new java.awt.Dimension(100, 0));
        dateFrom.setOpaque(false);
        dateFrom.setPreferredSize(new java.awt.Dimension(112, 0));
        dateFrom.setLayout(new java.awt.BorderLayout());

        dateTo.setMaximumSize(new java.awt.Dimension(112, 2147483647));
        dateTo.setMinimumSize(new java.awt.Dimension(100, 0));
        dateTo.setOpaque(false);
        dateTo.setPreferredSize(new java.awt.Dimension(112, 0));
        dateTo.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel5.setText("Stanice");

        station.setModel(GUI.MYOBJECTS.MyComboBox.getCombo(DB.Queries.ComboBox.getStations(true)));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel6.setText("Linka");

        line.setModel(GUI.MYOBJECTS.MyComboBox.getCombo(DB.Queries.ComboBox.getLines(true)));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel7.setText("Obvod");

        area.setModel(GUI.MYOBJECTS.MyComboBox.getCombo(DB.Queries.ComboBox.getAreas(true)));

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel9.setText("Událost");

        event.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Pád osoby do kolejiště", "Srážka s osobou", "Zachycení osoby soupravou", "Zaběhnuté zvíře", "Uvíznutí osoby" }));

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel10.setText("Příčina");

        reason.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "neopatrnost", "pokus o sebevraždu", "předmět v kolejišti" }));

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel11.setText("Zranění");

        injury.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "bez zranění", "lehké", "těžké", "smrt" }));

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel12.setText("Zpoždění");

        jLabel13.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel13.setText("Pohlaví");

        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "muž", "žena" }));

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel14.setText("Věk");

        jBtnSearch.setText("Vyhledej");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });

        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        age.setToolTipText("");

        SqlDateModel model1 = new SqlDateModel();
        Properties p1 = new Properties();
        p1.put("text.today", "Today");
        p1.put("text.month", "Month");
        p1.put("text.year", "Year");
        JDatePanelImpl datePanel1 = new JDatePanelImpl(model1, p1);
        datePicker1 = new JDatePickerImpl(datePanel1, new DateLabelFormatter());
        dateFrom.add(datePicker1);
        SqlDateModel model2 = new SqlDateModel();
        Properties p2 = new Properties();
        p2.put("text.today", "Today");
        p2.put("text.month", "Month");
        p2.put("text.year", "Year");
        JDatePanelImpl datePanel2 = new JDatePanelImpl(model2, p2);
        datePicker2 = new JDatePickerImpl(datePanel2, new DateLabelFormatter());
        dateTo.add(datePicker2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(station, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(line, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(event, 0, 0, Short.MAX_VALUE)
                    .addComponent(reason, 0, 199, Short.MAX_VALUE)
                    .addComponent(injury, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delay, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(age)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(station, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addComponent(event, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel10)
                .addGap(0, 0, 0)
                .addComponent(reason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel11)
                .addGap(0, 0, 0)
                .addComponent(injury, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(25, 25, 25)))
                .addComponent(jBtnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnReset)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel1);

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel15.setText("Mapa sítě metra");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout mapSearchViewer1Layout = new javax.swing.GroupLayout(mapSearchViewer1);
        mapSearchViewer1.setLayout(mapSearchViewer1Layout);
        mapSearchViewer1Layout.setHorizontalGroup(
            mapSearchViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        mapSearchViewer1Layout.setVerticalGroup(
            mapSearchViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(mapSearchViewer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(mapSearchViewer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable1.setModel(GUI.MYOBJECTS.MyTableModel.buildTableModel(DB.Queries.Incident.getIncidents(ta)));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showIncident(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(GUI.MYOBJECTS.MyTableModel.buildTableModel(DB.Queries.Aggregation.getStats()));
        jScrollPane2.setViewportView(jTable2);

        jLabel16.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel16.setText("Statistika");

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setText("Vyhledávání");

        jBtnNewIncident.setText("Vložit incident");
        jBtnNewIncident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNewIncidentActionPerformed(evt);
            }
        });

        jBtnDelFound.setText("Smazat nalezené");
        jBtnDelFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelFoundActionPerformed(evt);
            }
        });

        jBtnUpdate.setText("Vynulovat zpoždění nalezeným");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnDelFound)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnNewIncident)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnNewIncident)
                            .addComponent(jBtnDelFound)
                            .addComponent(jBtnUpdate)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * Zobrazí modální okno pro úpravu incidentu po kliknutí na řádek tabulky.
	 * @param evt předaná událost
	 */
    private void showIncident(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showIncident
		// číslo řádku daného incidentu
		int row = jTable1.rowAtPoint(evt.getPoint());
		
		// vytvoření okna s incidentem
		Main.dIncident = new Incident(Main.TopLevelWindow, true);
		
		// získání ID incidentu v DB
		int incidentID = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

		// inicializace otevřeného okna pro úpravu záznamu incidentu v DB
		Main.dIncident.initForUpdate(incidentID, this);
		Main.dIncident.setVisible(true);
		
    }//GEN-LAST:event_showIncident
	
	/**
	 * Resetuje pole vyhledávacího formuláře
	 * @param evt předaná událost
	 */
    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
		// inicializace fomuláře s datem
        Calendar c = Calendar.getInstance();
        int mYear = c.get(Calendar.YEAR);
        int mMonth = c.get(Calendar.MONTH);
        int mDay = c.get(Calendar.DAY_OF_MONTH);

        // smazání zbývajících polí
        id.setText("");
		age.setText("");
		delay.setText("");
        datePicker1.getModel().setDate(mYear, mMonth-1, mDay);
        datePicker1.getModel().setSelected(true);
        datePicker2.getModel().setDate(mYear, mMonth, mDay);
        datePicker2.getModel().setSelected(true);	
        station.setSelectedIndex(0);
		line.setSelectedIndex(0);
		area.setSelectedIndex(0);
        event.setSelectedIndex(0);
        injury.setSelectedIndex(0);
        reason.setSelectedIndex(0);
        sex.setSelectedIndex(0);
		searchIncidents();
    }//GEN-LAST:event_jBtnResetActionPerformed
	
	/**
	 * Nastaví hodnoty vyhledávacího formuláře do struktury.
	 */
	public void setValStruct()
	{
		// uložení hodnot formuláře do struktury
        ta.I_id = (id.getText().isEmpty() ? -1 : Integer.parseInt(id.getText()));	
        ta.I_stanice = ((((MyComboBox)station.getSelectedItem()) == null) ? -1 : ((MyComboBox)station.getSelectedItem()).getValue());
        ta.I_vek = (age.getText().isEmpty() ? -1 : Integer.parseInt(age.getText()));
        ta.I_zpozdeni = (delay.getText().isEmpty() ? -1 : Integer.parseInt(delay.getText()));
        ta.I_udalost = event.getSelectedItem().toString();
        ta.I_zraneni = injury.getSelectedItem().toString();
		ta.O_id = ((((MyComboBox)area.getSelectedItem()) == null) ? -1 : ((MyComboBox)area.getSelectedItem()).getValue());
		ta.L_id = ((((MyComboBox)line.getSelectedItem()) == null) ? -1 : ((MyComboBox)line.getSelectedItem()).getValue());
		ta.I_pricina = reason.getSelectedItem().toString();
        ta.I_pohlavi = sex.getSelectedItem().toString();
        ta.I_dateFrom = (String) datePicker1.getJFormattedTextField().getText();
        ta.I_dateTo = (String) datePicker2.getJFormattedTextField().getText();
	}
	
	/**
	 * Vyhledá incidenty v DB dle zadaných údajů ve formuláři.
	 */
	public void searchIncidents()
	{
		// získání hodnot formuláře
		setValStruct();
				
		// aplikování filtru na tabulku a naplnění výsledky
        jTable1.setModel(GUI.MYOBJECTS.MyTableModel.buildTableModel(DB.Queries.Incident.getIncidents(ta)));
		
		// aplikování filtru na mapu
        mapSearchViewer1.setIncident(ta);
		
        try {
            // překreslení mapy
             mapSearchViewer1.loadFilteredObjectFromDb();
        } catch (Exception ex) {
            Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        mapSearchViewer1.repaint();
	}
	   
	/**
	 * Vyhledá incidenty v DB dle zadaných údajů ve formuláři.
	 * @param evt 
	 */
    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
		if( ValidateForm.validateValue(id, "\\d*") & 
			ValidateForm.validateValue(age, "\\d*") & 
			ValidateForm.validateValue(delay, "\\d*"))
		{
			searchIncidents();
		}
		
    }//GEN-LAST:event_jBtnSearchActionPerformed

	/**
	 * Vyvolání okna pro vytvoření nového incidentu.
	 * @param evt předaná událost
	 */
    private void jBtnNewIncidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNewIncidentActionPerformed
        // vytvoření nového okna
		Main.dIncident = new Incident(Main.TopLevelWindow, true);
		
		// inicializace okna pro vložení nového incidentu
		Main.dIncident.initForInsert(this);
		Main.dIncident.setVisible(true);
    }//GEN-LAST:event_jBtnNewIncidentActionPerformed

    private void jBtnDelFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelFoundActionPerformed
		setValStruct();
		int reply = JOptionPane.showConfirmDialog(null, "Opravdu smazat?", "Opravdu smazat?", JOptionPane.YES_NO_OPTION);
		if (reply == JOptionPane.YES_OPTION)
		{
			DB.Queries.Incident.deleteIncidents(ta);
			searchIncidents();	
		}
		
    }//GEN-LAST:event_jBtnDelFoundActionPerformed

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        setValStruct();
		int reply = JOptionPane.showConfirmDialog(null, "Opravdu vynulovat?", "Opravdu vynulovat?", JOptionPane.YES_NO_OPTION);
		if (reply == JOptionPane.YES_OPTION)
		{
			DB.Queries.Incident.groupUpdateIncidents(ta);
			searchIncidents();
		}
		
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    public MapSearchViewer getMapSearchViewer(){
        return mapSearchViewer1;
    }
    
    public void setComboBoxs(){
        station.setModel(GUI.MYOBJECTS.MyComboBox.getCombo(DB.Queries.ComboBox.getStations(true)));
        line.setModel(GUI.MYOBJECTS.MyComboBox.getCombo(DB.Queries.ComboBox.getStations(true)));
        area.setModel(GUI.MYOBJECTS.MyComboBox.getCombo(DB.Queries.ComboBox.getStations(true)));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JComboBox<String> area;
    private javax.swing.JPanel dateFrom;
    private javax.swing.JPanel dateTo;
    private javax.swing.JTextField delay;
    private javax.swing.JComboBox<String> event;
    private javax.swing.JTextField id;
    private javax.swing.JComboBox<String> injury;
    private javax.swing.JButton jBtnDelFound;
    private javax.swing.JButton jBtnNewIncident;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> line;
    private GUI.PANELS.MapSearchViewer mapSearchViewer1;
    private javax.swing.JComboBox<String> reason;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JComboBox<String> station;
    // End of variables declaration//GEN-END:variables
}


