/**
 * Projekt do předmětu PDB (2016/2017) - Prostorové, multimediální a temporální 
 * databáze: Metro Accident Databse
 * Autoři: Petr Staněk (xstane34), 
           František Matečný (xmatec00),
           Jakub Stejskal (xstejs24)
 * Datum:  12.12.2016
 * Verze:  1.0
 */
package GUI;

import GUI.WINDOW.Incident;
import DB.DBConnection;
import DB.Objects.SpatialObjects;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 * Hlavní třída aplikace.
 */
public class Main extends javax.swing.JFrame {

	public static DBConnection db; // ukazatel na objekt s připojením do DB
	public static Incident dIncident; // ukazatel na okno pro vytvoření/editaci incidentu
	public static Main TopLevelWindow; // ukazatel na toto okno
	public static SpatialObjects spacialObjects = new SpatialObjects(); // obj. s prostrovými daty
    /**
     * Vytvoří hlavní okno programu.
     */
    public Main() {
        initComponents();
		TopLevelWindow = this;
		jMGInitDB.setEnabled(false);
		
		addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
				System.out.println("Ukončení spojení...");
                db.closeConnection();
            }
        });
   
		// nastavení parametrů okna
        this.setTitle("Metro Accidents Database");
        setSize(350,400);
        this.setLocationRelativeTo(null);  // vycentrování okna

		// otevření okna pro přihlášení
        JPanel g = new Login(this);
       
		// příprava okna pro zobrazení
		this.getContentPane().removeAll();
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(g);
        this.getContentPane().validate();
        this.getContentPane().repaint();
        setVisible(true);	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMGInitDB = new javax.swing.JMenu();
        jMIInitEmptyDB = new javax.swing.JMenuItem();
        jMIInitExampleDB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMGInitDB.setText("Inicializace DB");

        jMIInitEmptyDB.setText("Inicializovat prázdnou DB");
        jMIInitEmptyDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInitEmptyDBActionPerformed(evt);
            }
        });
        jMGInitDB.add(jMIInitEmptyDB);

        jMIInitExampleDB.setText("Inicializovat vzorovou DB");
        jMGInitDB.add(jMIInitExampleDB);

        jMenuBar1.add(jMGInitDB);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIInitEmptyDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInitEmptyDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIInitEmptyDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
		
		/* Create and test DB connection */
		db = new DBConnection();		
		
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu jMGInitDB;
    public javax.swing.JMenuItem jMIInitEmptyDB;
    public javax.swing.JMenuItem jMIInitExampleDB;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
