/**
 * Projekt do předmětu PDB (2016/2017) - Prostorové, multimediální a temporální 
 * databáze: Metro Accident Databse
 * Autoři: Petr Staněk (xstane34), 
           František Matečný (xmatec00),
           Jakub Stejskal (xstejs24)
 * Datum:  12.12.2016
 * Verze:  1.0
 */
package GUI;

import DB.Objects.SpatialObjects;
import DB.Queries.Spatial;
import java.awt.Color;
import java.net.URL;
import javax.swing.UIManager;

/**
 * Třída se všemi záložkami hlavního okna.
 */
public class Tabs extends javax.swing.JPanel {
    /**
     * Vytvoří hlavní panel.
     */
    public Tabs() {
		UIManager.put("nimbusBlueGrey", Color.LIGHT_GRAY);
        initComponents();
		Main.TopLevelWindow.jMIInitEmptyDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initEmptyDB();
            }
        });
		
		Main.TopLevelWindow.jMIInitExampleDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initExampleDB();
            }
        });
    }
	
	/**
	 * Inicializuje DB bez dat.
	 */
	private void initEmptyDB()
	{
		String path = "/cz/vutbr/fit/pdb/project01/queries/InitEmpty.sql";
		URL urlPath = getClass().getResource(path);
                
                path = "/cz/vutbr/fit/pdb/project01/queries/procedure.sql";
		URL urlPath1 = getClass().getResource(path);
		System.out.println("=================================================");
		System.out.println("Smazání DB:");
		DB.Queries.Spatial.initDB(urlPath, urlPath1);
		System.out.println("=================================================");
                
                Main.spacialObjects.listPoints.clear();
                Main.spacialObjects.listPolygons.clear();
                Main.spacialObjects.listPolylines.clear();
                Main.spacialObjects.listRectangles.clear();
                Spatial.loadObjectFromDb();
                
                overview.getSearch().searchIncidents();
                overview.getSearch().setComboBoxs();
                overview.getSearch().repaint();
                overview.getSearch().getMapSearchViewer().loadFilteredStationFromDb();
                overview.getSearch().getMapSearchViewer().repaint();
                
                overview.getSummary().setComboBoxs();
                overview.getSummary().repaint();
                overview.getSummary().getMapSummatyViewer().repaint();
                
                map.repaint();  
                map.getMapPanel().repaint();
                System.out.println("konec");
	}
	
	/**
	 * Incializuje vzorová data do DB.
	 */
	private void initExampleDB()
	{
		String path = "/cz/vutbr/fit/pdb/project01/queries/InitExample.sql";
		URL urlPath = getClass().getResource(path);
		DB.Queries.Spatial.initDB(urlPath, null);
                
                Main.spacialObjects.listPoints.clear();
                Main.spacialObjects.listPolygons.clear();
                Main.spacialObjects.listPolylines.clear();
                Main.spacialObjects.listRectangles.clear();
                Spatial.loadObjectFromDb();
                
                overview.getSearch().searchIncidents();
                overview.getSearch().setComboBoxs();
                overview.getSearch().repaint();
                overview.getSearch().getMapSearchViewer().loadFilteredStationFromDb();
                overview.getSearch().getMapSearchViewer().repaint();
                
                overview.getSummary().setComboBoxs();
                overview.getSummary().repaint();
                overview.getSummary().getMapSummatyViewer().repaint();
                
                map.repaint();  
                map.getMapPanel().repaint();
                System.out.println("konec");
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        Main_TabbedPane = new javax.swing.JTabbedPane();
        overview = new GUI.TABS.Overview();
        map = new GUI.TABS.Map();
        help = new GUI.TABS.Help();

        jLabel1.setText("jLabel1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        Main_TabbedPane.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        Main_TabbedPane.setOpaque(true);

        overview.setMinimumSize(new java.awt.Dimension(998, 800));
        overview.setPreferredSize(new java.awt.Dimension(998, 800));
        Main_TabbedPane.addTab("Přehled incidentů", overview);
        Main_TabbedPane.addTab("Mapové podklady", map);
        Main_TabbedPane.addTab("Nápověda", help);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main_TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 652, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTabbedPane Main_TabbedPane;
    GUI.TABS.Help help;
    javax.swing.JLabel jLabel1;
    javax.swing.JMenu jMenu1;
    javax.swing.JMenu jMenu2;
    javax.swing.JMenu jMenu3;
    javax.swing.JMenu jMenu4;
    javax.swing.JMenu jMenu5;
    javax.swing.JMenu jMenu6;
    javax.swing.JMenu jMenu7;
    javax.swing.JMenu jMenu8;
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JMenuBar jMenuBar2;
    javax.swing.JMenuBar jMenuBar3;
    javax.swing.JPopupMenu jPopupMenu1;
    GUI.TABS.Map map;
    GUI.TABS.Overview overview;
    // End of variables declaration//GEN-END:variables
}
